In [2]:
import pandas as pd
data1=pd.read_csv("./telecom.csv")

In [33]:
data1.head()

state  account length  area code phone number international plan  \
0    KS             128        415     382-4657                 no   
1    OH             107        415     371-7191                 no   
2    NJ             137        415     358-1921                 no   
3    OH              84        408     375-9999                yes   
4    OK              75        415     330-6626                yes   

  voice mail plan  number vmail messages  total day minutes  total day calls  \
0             yes                     25              265.1              110   
1             yes                     26              161.6              123   
2              no                      0              243.4              114   
3              no                      0              299.4               71   
4              no                      0              166.7              113   

   total day charge  ...  total eve calls  total eve charge  \
0             45.07  ...               99             16.78   
1             27.47  ...              103             16.62   
2             41.38  ...              110             10.30   
3             50.90  ...               88              5.26   
4             28.34  ...              122             12.61   

   total night minutes  total night calls  total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   total intl minutes  total intl calls  total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   customer service calls  churn  
0                       1  False  
1                       1  False  
2                       0  False  
3                       2  False  
4                       3  False  

[5 rows x 21 columns]

In [34]:
X = data1.iloc[:,6:20].values
X

array([[ 25.  , 265.1 , 110.  , ...,   3.  ,   2.7 ,   1.  ],
       [ 26.  , 161.6 , 123.  , ...,   3.  ,   3.7 ,   1.  ],
       [  0.  , 243.4 , 114.  , ...,   5.  ,   3.29,   0.  ],
       ...,
       [  0.  , 180.8 , 109.  , ...,   6.  ,   3.81,   2.  ],
       [  0.  , 213.8 , 105.  , ...,  10.  ,   1.35,   2.  ],
       [ 25.  , 234.4 , 113.  , ...,   4.  ,   3.7 ,   0.  ]])

In [35]:

Y=data1.iloc[:,20].values
Y

array([False, False, False, ..., False, False, False])

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1, random_state=101)

In [37]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB().fit(X_train, Y_train)

In [40]:
import numpy as np

Y_pred = model.predict(X_test)
Y_pred

array([False,  True,  True, False, False,  True, False,  True, False,
       False, False,  True,  True, False, False,  True,  True, False,
       False, False, False, False, False,  True, False, False,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True, False, False, False, False,  True, False, False, False,
       False, False, False, False, False,  True, False,  True, False,
       False, False,  True,  True,  True,  True, False, False,  True,
        True, False,  True,  True,  True,  True,  True, False, False,
        True, False,  True, False,  True,  True, False,  True, False,
       False,  True, False,  True, False,  True, False,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False,  True,  True, False, False,  True, False,  True,
        True, False, False, False, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False,  True,
       False, False,

In [43]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y_test, Y_pred))
print(classification_report(Y_test, Y_pred))

[[172 105]
 [ 28  29]]
              precision    recall  f1-score   support

       False       0.86      0.62      0.72       277
        True       0.22      0.51      0.30        57

    accuracy                           0.60       334
   macro avg       0.54      0.56      0.51       334
weighted avg       0.75      0.60      0.65       334

